### ISSUE TITLE
 Can we stop needing the original test?

### ISSUE THREAD

**Issue by jogobom** [FairlyLinearDynamics/YoCode#118]
If we used git to tell us whether anything has been modified, we might not need the original test at all.

If applicant has made commits - we know they changed things and can ask git what it was.
If applicant has not used git but the repo is still in the state we sent it out - `git status` will tell us what they changed.
If applicant has deleted the repo somehow - that's a red flag in itself so it's probably okay to say there was a problem.

This would make YoCode easier to use because it would only need one parameter, the modified test.

**Comment by SerCoach1** [comment]
Create a class that gets all the files from an unmodified test (with git, possibly with LibGit2Sharp?) so we could pass them to other checks instead of having to specify the original test int the run parameters
