### ISSUE TITLE
Make CodeCoverageCheck more accurate

### ISSUE THREAD

**Issue by mataszilaitis** [FairlyLinearDynamics/YoCode#145]
Chris recommended that we should exclude Program.cs and Startup.cs class when testing for code coverage, because it gives us inaccurate results. Even really bad applicants sometimes get 70 percent and up for this feature. There is no consistency in data and therefore it is hard to decide what's a good score and what's not

**Comment by SerCoach1** [comment]
Doesn't look like it's possible to exclude those classes (nothing we tried worked, but then again, we're bad at this)

**Comment by jogobom** [comment]
I made an example that shows how to read the values we care about out of the JSON coverage report. I think we could use that instead of only reading the overall result from the report.
