### ISSUE TITLE
Project Run feature passes even when the project doesn't run

### ISSUE THREAD

**Issue by mataszilaitis** [FairlyLinearDynamics/YoCode#148]
### Steps to reproduce

Remove Program.cs and Startup.cs files from hash 64CDB401BE4698209F62D8FC18661D748858BE9AEFC28FA6D529899BF9357531 and run YoCode.

### Expected result

Project Run should fail and throw something like this
![image](https://user-images.githubusercontent.com/7968437/44271817-112d1880-a233-11e8-8e1f-48068dc1a0e7.png)

^ This is the output I get when running the program from command line

### Observed result

![image](https://user-images.githubusercontent.com/7968437/44271877-328e0480-a233-11e8-8b70-60fe5fa3bec8.png)

### Suggestion

Check the ProjectRunner.cs class

**Comment by SerCoach1** [comment]
possible cause: dotnet clean throws "access is denied" warning and refuses to delete certain files
