### ISSUE TITLE
IanR crash when using YoCode

### ISSUE THREAD

**Issue by jogobom** [FairlyLinearDynamics/YoCode#171]
As discussed in Slack: https://nonlinear.slack.com/archives/CBASJPV5W/p1535013533000100

Zip file for Ian's project should be arriving soon so we can test it.

**Comment by mataszilaitis** [comment]
@jogobom , did he use the version for github or the one sent initially? Because Drew ran it without problems yesterday and it seems like this error should occur every time

**Comment by jogobom** [comment]
![image](https://user-images.githubusercontent.com/1519910/44516511-2daad400-a6bd-11e8-9fc0-b83ffadcc226.png)
Same version that I'm running, unless the version numbering is not working.

**Comment by jogobom** [comment]
That picture came from IanR btw.
