### ISSUE TITLE
Refactor Output/ErrorOutput in FeatureEvidence class

### ISSUE THREAD

**Issue by iLigonis** [FairlyLinearDynamics/YoCode#174]
"Output"; "ErrorOutput" variables are not used by majority of classes that reference FeatureEvidence. Try removing these fields from FeatureEvidence

**Comment by jogobom** [comment]
Also possible:
 * Better use of Passed, Failed, Inconclusive
 * `FeatureTitle` not needed?
 * SetPassed, SetFailed, SetInconclusive
