### ISSUE TITLE
Categorise our tests better, including "gateways"

### ISSUE THREAD

**Issue by jogobom** [FairlyLinearDynamics/YoCode#181]
Project Build and Project Run are like Files Changed, they are checks that must be passed or the applicant has just failed 100%. They are effectively "gateways". If failed, the applicant failed (0% or F-) and no more tests should be run. If passed, they should not contribute to the score, they should just let the other tests continue.

Solution File Exists is another example. There may be others, we'd have go through them in detail.

By treating these checks differently, it frees up the score weighting system to really reflect the more subtle checks, like duplication and code coverage, and would probably allow us to weight those better and give better scoring.

**Comment by mataszilaitis** [comment]
Would that be a property in the FeatureEvidence class, an enum possibly? @jogobom

**Comment by jogobom** [comment]
I'm not sure. I'd have to look into it.
