### ISSUE TITLE
FeatureTitleStorage looks for wrong check when failing gateway checks (see screenshot)

### ISSUE THREAD

**Issue by SerCoach1** [FairlyLinearDynamics/YoCode#230]
![image](https://user-images.githubusercontent.com/31220038/45105076-68842180-b12b-11e8-9c58-5c5c8244612d.png)

**Comment by mataszilaitis** [comment]
Worth to mention that this is only happening when there is a leftover `dotnet.exe` process. Otherwise program runs without problems. This is concerning

**Comment by jogobom** [comment]
It's not only when there's a leftover dotnet, it's whenever a gateway check fails.
