### ISSUE TITLE
Try to talk to the web controller endpoint

### ISSUE THREAD

**Issue by jogobom** [FairlyLinearDynamics/YoCode#33]
If we worked out which port it is running on in #32 then try to talk to the web API on that port. Or perhaps we could tell it which port to run on. But either way, when it is running, see if we can make a web API request to convert certain values and check the reply.

**Comment by WilkaH** [comment]
For getting this going, [Fiddler](https://www.telerik.com/fiddler) and [Postman](https://www.getpostman.com/) are good tools let you see what's going on before you write any code

**Comment by mataszilaitis** [comment]
It means that we have to keep ProjectRunner process running until we complete the web controller endpoint check

**Comment by mataszilaitis** [comment]
- [ ] Make killing of the `ProjectRunner` class an option 
- [ ] Get `action` names from the HTML file and store them in a list
- [ ] Prepare values which we want to test and store them in a list
- [ ] Loop through both lists and compare values
